### ISSUE TITLE
Create HTML Elements, and query Zomato

### ISSUE THREAD

**Issue by Fleerless** [Fleerless/Bootcamp-Group-Project#4]
##User Story:
As a user I want to be able to search for dining options in an area.

##Acceptance Criteria
- [x] Create all related search elements (Hard code Denver to start)
- [x] Ping Zomato API for a response to the search criteria
- [x] Format API response data into an object

**Comment by cleve716** [comment]
not seeing a text with Zoom number...



Sent from my portable telephone machine



-------- Original message --------
