### ISSUE TITLE
Gererate the map image - place on page

### ISSUE THREAD

**Issue by Fleerless** [Fleerless/Bootcamp-Group-Project#5]
##User Story
As a user I want to see where the results are concentrated, so I can go to that area.

##Acceptance Criteria
- [x] Access Zomato results stores in object variable 
- [x] Populate page with a map centered on result location
- [x] Overlay Zomato results as a heatmap layer

**Comment by ahardy42** [comment]
I am working on this today.  I did a test-page using mapbox API and leaflet.js and it works! 

from the HTML i need: (found here as well: [https://leafletjs.com/examples/quick-start/](url)
Before writing any code for the map, you need to do the following preparation steps on your page:

Include Leaflet CSS file in the head section of your document:

` <link rel="stylesheet" href="https://unpkg.com/leaflet@1.4.0/dist/leaflet.css"
   integrity="sha512-puBpdR0798OZvTTbP4A8Ix/l+A4dHDD0DGqYW6RQ+9jxkRFclaxxQb/SJAWZfWAkuyeQUytO7+7N4QKrDh+drA=="
   crossorigin=""/>`

Include Leaflet JavaScript file **after** Leaflet’s CSS:

`<script src="https://unpkg.com/leaflet@1.4.0/dist/leaflet.js"
   integrity="sha512-QVftwZFqvtRNi0ZyCtsznlKSWOStnDORoefr1enyq5mVL4tmKB3S/EnC3rRJcxCPavG10IcrVGSmPh6Qw5lwrg=="
   crossorigin=""></script>`

include references to two files that I will add to the javascript directory later: 
1. heatmap.js
2. leaflet-heatmap.js

Put a div element with a certain id where you want your map to be:

 `<div id="mapid"></div>`

Make sure the map container has a defined height, for example by setting it in CSS:

`#mapid { height: 180px; }`

from the zomato results, I need two things: 
1. a variable that holds the restaurants object and a path to the location lat / long for each result
2. a variable that holds the lat / long result for the center point of the search
